### ISSUE TITLE
Cannot load legends file after new beta update

### ISSUE THREAD

**Issue by Padex98** [Kromtec/LegendsViewer-Next#37]
So, the game's beta updated a few days ago, and since then, the program is unable to load the files exported from legends mode. It gets stuck in an infinite loading loop.

**Comment by henges** [comment]
The exception that gets thrown is something like:

```
System.Xml.XmlException: '', hexadecimal value 0x11, is an invalid character. Line 26384, position 16.
    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlReader.ReadStartElement()
   at LegendsViewer.Backend.Legends.Parser.XmlParser.ParsePropertyAsync() in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\Parser\XMLParser.cs:line 250
   at LegendsViewer.Backend.Legends.Parser.XmlParser.ParsePropertyAsync() in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\Parser\XMLParser.cs:line 265
   at LegendsViewer.Backend.Legends.Parser.XmlParser.ParseItemPropertiesAsync() in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\Parser\XMLParser.cs:line 217
   at LegendsViewer.Backend.Legends.Parser.XmlParser.ParseSectionAsync() in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\Parser\XMLParser.cs:line 143
   at LegendsViewer.Backend.Legends.Parser.XmlParser.ParseAsync() in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\Parser\XMLParser.cs:line 62
   at LegendsViewer.Backend.Legends.World.ParseAsync(String xmlFile, String xmlPlusFile, String historyFile, String sitesAndPopulationsFile, String mapFile) in <dir>\LegendsViewer-Next\LegendsViewer.Backend\Legends\World.cs:line 122
   at LegendsViewer.Backend.Tests.LegendsParserTests.Test_ParseLegendsXmlFile_Success() in <dir>\LegendsViewer-Next\LegendsViewer.Backend.Tests\LegendsParserTests.cs:line 18
```

The relevant line of my input XML is this:

![image](https://github.com/user-attachments/assets/f5437534-4fda-4a3d-a70e-a6648c9eb158)

This is one of the new types of artifact generated in mysterious lairs, used in the 'chosen' quests in adventure mode. It appears as if their names can use control characters from CP437, which are rejected by the default XML text reader. It's worth noting these are actually rendered in games as chevrons, e.g. something like '<primal cloudstuff short sword>'.

A solution that worked for me locally was creating a wrapper for the XML file stream that discards input based on a predicate:

```csharp
public class FilteredStream : Stream
{
    private readonly Stream _baseStream;
    // if true, discard byte
    private readonly Func<byte, bool> _predicate;

    public FilteredStream(Stream baseStream, Func<byte, bool> predicate)
    {
        _baseStream = baseStream ?? throw new ArgumentNullException(nameof(baseStream));
        _predicate = predicate ?? throw new ArgumentNullException(nameof(predicate));
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        byte[] tempBuffer = new byte[count];
        int bytesRead = _baseStream.Read(tempBuffer, 0, count);

        if (bytesRead == 0) return 0;

        int wrote = 0;
        for (int i = 0; i < bytesRead; i++)
        {
            if (_predicate(tempBuffer[i]))
            {
                continue;
            }

            buffer[offset + wrote] = tempBuffer[i];
            wrote++;
        }

        return wrote;
    }
    // ...other simple delegate/unsupported methods
}
```

and then updating the `XmlParser`'s constructor to use it, dropping characters in the control range (0-31):

```csharp
XmlReader = XmlReader.Create(new FilteredStream(new FileStream(xmlFile, FileMode.Open), b => b < 32), /* ... */ );
```

But this feels like a hacky solution, because those characters are ultimately a proper part of the item name.

**Comment by Kromtec** [comment]
Thanks @henges for providing so much detail and an already working solution. Even if it is hacky I used a slightly altered version of your solution to still get the chevrons in, but kept the rest. 
The real problem is the export itself, I hope it gets officially fixed by ToadyOne or Putnam.
